# To install pip, Docker, Docker compose, Docker SDK for Python and all corresponding dependencies
# Also creating the group docker and adding user to the group
# Copying the petclinic application repo from source machine(local) to host machine (VM)
# Additionally deploying the petclinic application using docker compose 

- name: VM configuration
  hosts: becode@vmsdt-pisharodi.becode.org
  become: true
  gather_facts: false
  #become_user: becode
  vars:
    docker_user: becode
    docker_group: docker

  tasks:
    - name: Install python pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes
      when: false
    
    - name: Installing system packages needed for docker 
      ansible.builtin.apt: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - ca-certificates 
        - curl 
        - gnupg
        - lsb-release
      when: false

    - name: Add Dockerâ€™s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: false

    - name: Setting up repo for docker
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        
      when: false

    - name: Instaling docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
      when: false

   # Manage Docker as a non-root user 

    - name: Creating a docker group
      group:
        name: "{{ docker_group }}"
        state: present
      become: yes
      #become_user: "{{ docker_user }}"
      #become_method: sudo
      when: true

    - name: Adding user and to docker group
      user: 
        name: "{{ docker_user }}"
        groups: "{{ docker_group }}"
        state: present
        append: yes
      #become: yes
      #become_user: "{{ docker_user }}"
      become_method: sudo
      when: true

    - name: Install Docker SDK for python
      pip:
        name: "{{ item }}"
        state : present
      loop: 
        - docker
        - docker-compose
        - jsondiff
      when: false

  # Method: 1 Copying repo from local machine to host machine
    
    - name: Copying the petclinic application to remote machine
      ansible.builtin.copy:
        owner: becode
        src: /Users/nitya/Docker_Workspace/Webapp/jgsu-spring-petclinic/docker-compose.yml
        dest: /home/becode/jgsu-spring-petclinic/docker-compose.yml
      when: false

  # Method: 2 Cloning the repo from github
    - name: Cloning the petclinic repo from github
      ansible.builtin.git:
       # owner: becode
        repo: https://github.com/nityapisharodi/jgsu-spring-petclinic.git
        dest: /home/becode/jgsu-spring-petclinic
        clone: yes
        #version: master
      when: false


  # Running the 'docker compose up'

    - name: Petclinic container
      community.docker.docker_compose:
        project_src: jgsu-spring-petclinic
        project_name: jgsu-spring-petclinic
        state: present
      when: false
